before_script:
  - apt-get -qq update && apt-get -y -qq install texlive-latex-base xzdec
  - mkdir texmf
  - tlmgr init-usertree
  - tlmgr install tcolorbox
  - pdflatex -version
  - cd docs
  - cp ../KGCOEReport.cls .

after_script:
  - rm docs/KGCOEReport.cls

.generic_sample: &generic_def
  script:
    - pdflatex $CI_BUILD_NAME.tex
  artifacts:
    paths:
      - docs/$CI_BUILD_NAME.pdf

CMPE_sample:
  <<: *generic_def

EEEE_sample:
  <<: *generic_def
