before_script:
  - apt-get -qq update && apt-get -y -qq install texlive-latex-base
  - tlmgr install tcolorbox
  - pdflatex -version
  - cd docs
  - cp ../KGCOEReport.cls .

CMPE_sample:
  script:
    - pdflatex CMPE_sample.tex
  artifacts:
    paths:
      - docs/CMPE_sample.pdf
  after_script:
    - rm docs/KGCOEReport.cls

EEEE_sample:
  script:
    - pdflatex EEEE_sample.tex
  artifacts:
    paths:
    - docs/EEEE_sample.pdf
  after_script:
    - rm docs/KGCOEReport.cls
