before_script:
  - apt-get -qq update && apt-get -y -qq install texlive-latex-extra
  - pdflatex -version
  - cd docs
  - cp ../KGCOEReport.cls .

CMPE_sample:
  script:
    - pdflatex CMPE_sample.tex

EEEE_sample:
  script:
    - pdflatex EEEE_sample.tex