before_script:
  - apt-get -qq update && apt-get -y -qq install texlive-latex-extra
  - pdflatex -version
  - cd docs
  - cp ../KGCOEReport.cls .

CMPE_sample:
  script:
    - pdflatex CMPE_sample.tex
  artifacts:
    paths:
      - CMPE_sample.pdf
  after_script:
    - rm KGCOEReport.cls

EEEE_sample:
  script:
    - pdflatex EEEE_sample.tex
  artifacts:
    paths:
    - EEEE_sample.pdf
  after_script:
    - rm KGCOEReport.cls
